export const DEPOSIT_ADD_ITEM = 'DEPOSIT_ADD_ITEM';
export const DEPOSIT_REMOVE_ITEM = 'DEPOSIT_REMOVE_ITEM';
export const DEPOSIT_SAVE_SHIPPING = 'DEPOSIT_SAVE_SHIPPING';
export const DEPOSIT_SAVE_PAYMENT = 'DEPOSIT_SAVE_PAYMENT';