export const PUPPY_LIST_REQUEST = 'PUPPY_LIST_REQUEST';
export const PUPPY_LIST_SUCCESS = 'PUPPY_LIST_SUCCESS';
export const PUPPY_LIST_FAIL = 'PUPPY_LIST_FAIL';

export const PUPPY_DETAILS_REQUEST = 'PUPPY_DETAILS_REQUEST';
export const PUPPY_DETAILS_SUCCESS = 'PUPPY_DETAILS_SUCCESS';
export const PUPPY_DETAILS_FAIL = 'PUPPY_DETAILS_FAIL';

export const PUPPY_SAVE_REQUEST = 'PUPPY_SAVE_REQUEST';
export const PUPPY_SAVE_SUCCESS = 'PUPPY_SAVE_SUCCESS';
export const PUPPY_SAVE_FAIL = 'PUPPY_SAVE_FAIL';

export const PUPPY_DELETE_REQUEST = 'PUPPY_DELETE_REQUEST';
export const PUPPY_DELETE_SUCCESS = 'PUPPY_DELETE_SUCCESS';
export const PUPPY_DELETE_FAIL = 'PUPPY_DELETE_FAIL';